#!/usr/bin/env python3
"""epic-coverage - the E4 gate of epic-flow (MC-017).

Diffs the union of fragment-owned outputs against the architecture's declared
outputs and writes <epic>/40-coverage.md. Exit 1 on any UNCLAIMED remainder
(a declared output no fragment owns) or any OVER-CLAIM (one output owned by
two fragments - duplication scheduled in advance). Undeclared claims (a
fragment owns an output the architecture never declared) are WARNINGS: they
mean 20-architecture.md is stale, and the honest fix is a plan edit.

Strict input format, stdlib only:
  20-architecture.md  ->  a "## Declared outputs" section of lines "- <kind>: <name>"
  30-fragments/*.md   ->  frontmatter between --- markers with a block list:
                            outputs:
                              - <kind>: <name>
Kinds: schema | route | file | artifact | job.
"""
import re, sys, io
from pathlib import Path

KINDS = {"schema", "route", "file", "artifact", "job"}
OUT_RE = re.compile(r"^\s*-\s*(schema|route|file|artifact|job)\s*:\s*(\S.*?)\s*$")

def declared(arch_path: Path):
    if not arch_path.exists():
        sys.exit(f"epic-coverage: missing {arch_path}")
    outs, in_section = [], False
    for line in arch_path.read_text(encoding="utf-8").splitlines():
        if line.strip().lower() == "## declared outputs":
            in_section = True
            continue
        if in_section and line.startswith("## "):
            break
        if in_section:
            m = OUT_RE.match(line)
            if m:
                outs.append((m.group(1), m.group(2)))
    return outs

def fragment_claims(frag_dir: Path):
    claims = []  # (kind, name, fragment-id)
    for f in sorted(frag_dir.glob("*.md")):
        text = f.read_text(encoding="utf-8")
        m = re.match(r"^---\n(.*?)\n---", text, re.S)
        if not m:
            continue
        fm = m.group(1)
        fid_m = re.search(r"^id:\s*(\S+)", fm, re.M)
        fid = fid_m.group(1) if fid_m else f.stem
        in_outputs = False
        for line in fm.splitlines():
            if re.match(r"^outputs:\s*(\[\s*\])?\s*$", line):
                in_outputs = "[" not in line
                continue
            if in_outputs:
                om = OUT_RE.match(line)
                if om:
                    claims.append((om.group(1), om.group(2), fid))
                elif not line.startswith((" ", "\t")) or ":" in line.split("-")[0]:
                    in_outputs = False
    return claims

def main():
    if len(sys.argv) != 2:
        sys.exit("usage: epic-coverage.py <epic-folder>")
    epic = Path(sys.argv[1])
    decl = declared(epic / "20-architecture.md")
    claims = fragment_claims(epic / "30-fragments")

    owners = {}
    for kind, name, fid in claims:
        owners.setdefault((kind, name), []).append(fid)

    unclaimed  = [d for d in decl if d not in owners]
    overclaims = {k: v for k, v in owners.items() if len(v) > 1}
    undeclared = [k for k in owners if k not in decl]
    claimed    = [d for d in decl if d in owners and len(owners[d]) == 1]

    out = io.StringIO()
    out.write("# Coverage - GENERATED by tools/epic-coverage.py, never hand-edited\n\n")
    out.write("| output | status | owner(s) |\n|---|---|---|\n")
    for kind, name in decl:
        key = (kind, name)
        if key in overclaims:
            out.write(f"| {kind}: {name} | OVER-CLAIMED | {', '.join(overclaims[key])} |\n")
        elif key in owners:
            out.write(f"| {kind}: {name} | claimed | {owners[key][0]} |\n")
        else:
            out.write(f"| {kind}: {name} | **UNCLAIMED** | - |\n")
    for kind, name in undeclared:
        out.write(f"| {kind}: {name} | undeclared claim (warning) | {', '.join(owners[(kind,name)])} |\n")
    verdict = "PASS" if not unclaimed and not overclaims else "FAIL"
    out.write(f"\n**Verdict: {verdict}** - declared {len(decl)}, cleanly claimed "
              f"{len(claimed)}, unclaimed {len(unclaimed)}, over-claimed "
              f"{len(overclaims)}, undeclared {len(undeclared)}\n")
    (epic / "40-coverage.md").write_text(out.getvalue(), encoding="utf-8")
    print(out.getvalue())
    sys.exit(0 if verdict == "PASS" else 1)

if __name__ == "__main__":
    main()
